---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 719532276669947907-bc8ftH3Rhr8LXRvuTqtN4zRF5OaHWLs
:access_token_secret: ObbCAfhq725mgJK0yF1066rgJ6CYLq5mLY0upwXZdzBmM
